bootstrap_app='bootstrap'

folders=[
	'app/',
	'app/main/',
	'app/auth/',
	'app/static/css/',
	'app/static/css/auth/',
	'app/static/css/main/',
	'app/static/images/',
	'app/static/js/',
	'app/static/js/auth/',
	'app/static/js/auth/app/',
	'app/static/js/main/',
	'app/static/js/main/app/',
	'app/static/js/ext/',
	'app/templates/',
	'app/templates/auth/',
	'app/templates/main/',
	'tests/'	
]

files=[
	'manage.py',
	'config.py',
	'requirements.txt',
	'app/__init__.py',
	'app/models.py',
	'app/main/__init__.py',
	'app/main/views.py',
	'app/auth/__init__.py',
	'app/auth/views.py',
	'app/templates/auth/index.html',
	'app/templates/main/index.html'
]
